
$(document).ready(function(){$("#txtKey").keydown(function(event){if(event.keyCode==13){$("#btnSearch").click();}});var sortbox_State;$(".sortbox").mouseover(function(){var $this=$(this);window.clearTimeout(sortbox_State);sortbox_State=setTimeout(function(){$this.find(".group_read_layer").show();},200);}).mouseout(function(){var $this=$(this);window.clearTimeout(sortbox_State);sortbox_State=setTimeout(function(){$this.find(".group_read_layer").hide();},300);});var sortbox_State_level;$(".level_sortbox").mouseover(function(){var $this=$(this);window.clearTimeout(sortbox_State_level);sortbox_State_level=setTimeout(function(){$this.find(".group_read_layer").show();},200);}).mouseout(function(){var $this=$(this);window.clearTimeout(sortbox_State_level);sortbox_State_level=setTimeout(function(){$this.find(".group_read_layer").hide();},300);});});function hideBugBox(objId){$("#"+objId).fadeOut(300);}
$(function(){$.cookie("showType",null,{expires:-1,path:"/listen"});$("#gridtype").click(function(){$(".displaytype").css("background-position","-137px -26px");$.cookie("showType",null,{expires:-1,path:"/"});$("#topicList").show();$("#aricleList").hide();$(".filters").hide();$(".panel_title").text($(".panel_title").text().replace("听写","节目"));});$("#listtype").click(function(){$(".displaytype").css("background-position","-137px -1px");$.cookie("showType","listType",{expires:1,path:"/"});$("#topicList").hide();$("#aricleList").show();$(".filters").show();$(".panel_title").text($(".panel_title").text().replace("节目","听写"));});$("#btnSearch").click(function(){var txtKey=$.trim($("#txtKey").val());var lang=$("input[name='selLanguage']:checked").val();location.href="/search/?page=1&lang=all&key="+txtKey;return false;});if(location.hash=="#grid"){$("#gridtype").click();}
else if(location.hash=="#list"){$("#listtype").click();}})
$(function(){$.fn.lazyhover=function(fuc_on,fuc_out,de_on,de_out){var self=$(this);var flag=1;var h;var handle=function(elm){clearTimeout(h);if(!flag)self.removeData('timer');return flag?fuc_on.apply(elm):fuc_out.apply(elm)};var time_on=de_on||0;var time_out=de_out||500;var timer=function(elm){h&&clearTimeout(h);h=setTimeout(function(){handle(elm)},flag?time_on:time_out);self.data('timer',h)};self.hover(function(){flag=1;timer(this)},function(){flag=0;timer(this)})}
var canHide=true;$("#cls_pnlHeader").find(".layer_slideTitle").click(function(){$("#cls_pnlHeader").find(".current").removeClass("current");$(this).parents("li").addClass("current");});$("#cls_pnlHeader").find(".layer_slideTitle").lazyhover(function(){$("#cls_pnlHeader").find(".current").removeClass("current");$(this).parents("li").addClass("current");},function(){doHide();},90,200);$("#cls_pnlHeader").find(".layer_slideTitle").mouseover(function(){canHide=false;}).mouseout(function(){canHide=true;});$(".cls_pnlHeader_wrap").find('.layer_slideList').mouseover(function(){canHide=false;}).mouseout(function(){canHide=true;});if($("#clubHeader_pnl_user_oldHeader").length>0){$("#header").css({"height":"40px","padding-top":"12px","border-bottom":"1px solid #E8E8E8"});}
$(".cls_pnlHeader_wrap").find('.layer_slideList').lazyhover(function(){},function(){doHide();},200,200);BindTextChange($("#cls_txtHeadSearch"));function doHide(){if(canHide){$(".cls_pnlHeader_wrap").find(".current").removeClass("current");canHide=true;}}
$("#cls_header_AppSlide").find(".cls_header_AppSlide_Title").lazyhover(function(){$("#cls_header_AppSlide").removeClass("current");$("#cls_header_AppSlide").addClass("current");$(".cls_header_app_en").html("英语站");$(".cls_header_app_jp").html("日语站");$(".cls_header_app_fr").html("法语站");$(".cls_header_app_kr").html("韩语站");},function(){doHide();},200,200);$("#cls_header_AppSlide").find("ul").mouseover(function(){canHide=false;}).mouseout(function(){canHide=true;});$("#cls_header_AppSlide").find("ul").lazyhover(function(){},function(){doHide();},200,200);function BindTextChange(obj){$(obj).focus(function(){var real=$(this).attr("rel");if(real==$(this).val()){$(this).val("").removeClass("lightgray");}});$(obj).blur(function(){if($(this).val()==""){$(this).val($(this).attr("rel")).addClass("lightgray");}});if($.browser!=null&&$.browser.msie&&$.browser.version=='6.0'){$("#cls_pnlHeader").find(".menu").mouseover(function(){$(this).addClass("cls_headMenu_hover");PageSelect();}).mouseout(function(){$(this).removeClass("cls_headMenu_hover");PageSelect();});}}
$(".layer_slideTitle").each(function(){if($.browser!=null&&$.browser.msie&&$.browser.version=='6.0'){$(this).css("width",$(this).width()+10);}});$("#cls_btnSearch").click(function(e){var key=encodeURI($.trim($("#cls_txtHeadSearch").val()));var rel=$("#cls_txtHeadSearch").attr("rel");if(key==""||rel==key){return;}
window.open("http://bulo.hujiang.com/app/search/all/?key="+key,"_blank");});$("#cls_txtHeadSearch").keydown(function(e){if(e.keyCode==13){$("#cls_btnSearch").click();}});$("#cls_txtHeadSearch").focus(function(){$(this).parents(".cls_pnlSearch").addClass("hover");}).blur(function(){$(this).parents(".cls_pnlSearch").removeClass("hover");});PageSelect();$("#cls_headMenu_using .layer_AppList ul li:lt(12)").show();if($("#cls_headMenu_using .layer_AppList ul li").length<13){$(".moreApp").hide();}
$(".moreApp").click(function(){$("#cls_headMenu_using .layer_AppList ul li").slideDown("200");$(this).hide();});if($("#wrap").width()<1400){}else{$("#cls_pnlHeader").css("width","99%");}});function ReturnHead(isNew){$.post("/api/api_setHead.ashx?isNew="+isNew,function(result){window.location.reload();});}
function PageSelect(){if(document.URL.indexOf("com/home")>0){$("#cls_headMenu_home").addClass("cls_headMenu_hover");}
if(document.URL.indexOf("com/friends")>0||document.URL.indexOf("/friends/fans/")>0||document.URL.indexOf("/myfollows/")>0||document.URL.indexOf("/friends/area/")>0||document.URL.indexOf("/friends/mayknow/")>0||document.URL.indexOf("/app/friends/visitor/")>0){$("#cls_headMenu_myfriends").addClass("cls_headMenu_hover");}
if(document.URL.indexOf("com/app/list")>0){$("#cls_headMenu_using").addClass("cls_headMenu_hover");}
if(document.URL.indexOf("com/group")>0){$("#cls_headMenu_group").addClass("cls_headMenu_hover");}
if(document.URL.indexOf("com/msg/recent")>0||document.URL.indexOf("/msg/#/notice")>0){$(".li_msgList").addClass("cls_headMenu_hover");}
if(document.URL.indexOf("/menu")>0){$("#cls_headMenu_menu").addClass("cls_headMenu_hover");}
if(document.URL.indexOf("s.hujiang.com")>0){$("#cls_headMenu_s").addClass("cls_headMenu_hover");}
if(document.URL.indexOf("/u/")>0){$("#cls_headMenu_mybulo").addClass("cls_headMenu_hover");}
if(document.URL.indexOf("/setting/normal/")>0||document.URL.indexOf("/account/exchange/")>0){$("#cls_headMenu_pofile").addClass("cls_headMenu_hover");}}
function hjd_onShiftDictEnable(status){if(status){$("#hjdict_slide").addClass("on").text("划词").attr("title","划词已开启");}else{$("#hjdict_slide").removeClass("on").text("划词").attr("title","划词已关闭");}}
document.cookie="BuloMusicControl=0;path=/";document.cookie="BuloMusicTitle=0;path=/;expires=Sat, 31 Oct 1995 16:08:58 GMT";function CallDict(){tipsWindown('沪江小D<span style="font-weight:200;color:gray;">（使用快捷键Ctrl+F8可快速呼叫出查词窗口哦~）</span>','iframe:http://dict.hujiang.com/outapp/bulo/en.aspx','530','440','true','','false','text','/images/dict_demo.gif');}
var ingSenderBox=null;$(function(){if(HJ_New_BuloID>0){setTimeout("GetMsg();",3000);RefreshID=setInterval("GetMsg()",30000);}
ingSenderBox=new ingSender();ingSenderBox.callback_success=function(){ingSenderBox.showSuccess("发送成功！ <a style='margin:0px 5px 0px 10px' href='http://t.hujiang.com/'"+HJ_New_BuloID+"' class='noline' target='_blank'>查看碎碎&raquo;</a>",true,3000);};$(window).keydown(function(e){if(e.ctrlKey&&e.keyCode==119){var frame=$("#windown-close");if(frame.length>0){frame.click();}
else{CallDict();}}});$(".layer_cnt .link_headLogout").click(function(){try{document.cookie='ClubAuth=;path=/;domain=;expires=Thu, 01-Jan-1970 00:00:01 GMT';HJBulo.fun.setCookie('bulo_tips_201208_nc',null,1,'/');}
catch(e){};document.location.href='http://bulo.hujiang.com/logout?returnurl='+encodeURIComponent(document.location.href);return false;})
$("li.cls_headMenu_hover").removeClass("cls_headMenu_hover");if(isDict){setTimeout(function(){$.getScript("http://dict.hjenglish.com/app/js/dict_ajax.js");},2000);}});function ToolDictQuick(){tipsWindown('沪江小D <span style=font-weight:200;color:gray;>(使用快捷键Ctrl+F8可快速呼叫出查词窗口哦~)</span>','iframe:http://dict.hujiang.com/outapp/bulo/en.aspx','530','440','true','','false','text','/images/dict_demo.gif');}
(function($){$.toJSON=function(o){if(typeof(JSON)=='object'&&JSON.stringify)
return JSON.stringify(o);var type=typeof(o);if(o===null)
return"null";if(type=="undefined")
return undefined;if(type=="number"||type=="boolean")
return o+"";if(type=="string")
return $.quoteString(o);if(type=='object'){if(typeof o.toJSON=="function")
return $.toJSON(o.toJSON());if(o.constructor===Date){var month=o.getUTCMonth()+1;if(month<10)month='0'+month;var day=o.getUTCDate();if(day<10)day='0'+day;var year=o.getUTCFullYear();var hours=o.getUTCHours();if(hours<10)hours='0'+hours;var minutes=o.getUTCMinutes();if(minutes<10)minutes='0'+minutes;var seconds=o.getUTCSeconds();if(seconds<10)seconds='0'+seconds;var milli=o.getUTCMilliseconds();if(milli<100)milli='0'+milli;if(milli<10)milli='0'+milli;return'"'+year+'-'+month+'-'+day+'T'+
hours+':'+minutes+':'+seconds+'.'+milli+'Z"';}
if(o.constructor===Array){var ret=[];for(var i=0;i<o.length;i++)
ret.push($.toJSON(o[i])||"null");return"["+ret.join(",")+"]";}
var pairs=[];for(var k in o){var name;var type=typeof k;if(type=="number")
name='"'+k+'"';else if(type=="string")
name=$.quoteString(k);else
continue;if(typeof o[k]=="function")
continue;var val=$.toJSON(o[k]);pairs.push(name+":"+val);}
return"{"+pairs.join(", ")+"}";}};$.evalJSON=function(src){if(typeof(JSON)=='object'&&JSON.parse)
return JSON.parse(src);return eval("("+src+")");};$.secureEvalJSON=function(src){if(typeof(JSON)=='object'&&JSON.parse)
return JSON.parse(src);var filtered=src;filtered=filtered.replace(/\\["\\\/bfnrtu]/g,'@');filtered=filtered.replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,']');filtered=filtered.replace(/(?:^|:|,)(?:\s*\[)+/g,'');if(/^[\],:{}\s]*$/.test(filtered))
return eval("("+src+")");else
throw new SyntaxError("Error parsing JSON, source is not valid.");};$.quoteString=function(string){if(string.match(_escapeable)){return'"'+string.replace(_escapeable,function(a)
{var c=_meta[a];if(typeof c==='string')return c;c=a.charCodeAt();return'\\u00'+Math.floor(c/16).toString(16)+(c%16).toString(16);})+'"';}
return'"'+string+'"';};var _escapeable=/["\\\x00-\x1f\x7f-\x9f]/g;var _meta={'\b':'\\b','\t':'\\t','\n':'\\n','\f':'\\f','\r':'\\r','"':'\\"','\\':'\\\\'};})(jQuery);
var isclosed=false;var newData;function GetNewMsg(data,nosave){var result=data||{};$.extend(result,newData);var html="";if(data==null){return;}
if(data.tc>0){var tc_count=data.tc;if(tc_count>99){tc_count="99+";}
html+="<span class='tips_data_tc'><a class='noline fr' href=\"http://s.hujiang.com/atTopic\">点击查看</a>"+tc_count+"条论坛提醒<br /></span>";}
if(data.cc>0){var tc_count=data.cc;if(tc_count>99){tc_count="99+";}
html+="<span class='tips_data_cc'><a class='noline fr' class='noline' href=\"http://t.hujiang.com/comments\">点击查看</a>"+tc_count+"条新增评论<br /></span>";}
if(data.fc>0){var tc_count=data.fc;if(tc_count>99){tc_count="99+";}
html+="<span class='tips_data_fc'><a class='noline fr' href=\"http://t.hujiang.com/fans\">点击查看</a>"+tc_count+"位新增粉丝<br /></span>";}
if(data.ac>0){var tc_count=data.ac;if(tc_count>99){tc_count="99+";}
html+="<span class='tips_data_ac'><a class='noline fr' href=\"http://t.hujiang.com/atme\">点击查看</a>"+tc_count+"条新@信息<br /></span>";}
if(data.pc>0){var tc_count=data.pc;if(tc_count>99){tc_count="99+";}
html+="<span class='tips_data_pc'><a class='noline fr' href=\"http://bulo.hujiang.com/menu/sub/?click=1\">点击查看</a>"+tc_count+"个节目更新<br /></span>";}
if(data.mc>0){var tc_count=data.mc;if(tc_count>99){tc_count="99+";}
html+="<span class='tips_data_mc'><a class='noline fr' href=\"http://bulo.hujiang.com/msg/recent/?type=0\">点击查看</a><span class='tips_data_mcount'>"+tc_count+"</span>条新短消息<br /></span>";}
if(data.nc>0){var tc_count=data.nc;if(tc_count>99){tc_count="99+";}
html+="<span class='tips_data_nc'><a class='noline fr' href=\"http://bulo.hujiang.com/msg/#/notice\">点击查看</a>"+tc_count+"条新增通知<br /></span>";}
if(data.st_atme>0){var tc_count=data.st_atme;if(tc_count>99){tc_count="99+";}
html+="<span class='tips_data_stat'><a class='noline fr' href=\"http://st.hujiang.com/attopic/\">点击查看</a>"+tc_count+"条社团@消息<br /></span>";}
if(data.st_answer>0){var tc_count=data.st_answer;if(tc_count>99){tc_count="99+";}
html+="<span class='tips_data_stanswer'><a class='noline fr' href=\"http://st.hujiang.com/rm/\">点击查看</a>"+tc_count+"条社团新回复<br /></span>";}
if(html==""){$("#ing_push").hide();}
else{$("#ing_push").show();$("#push_cnt").html(html);try{$(".li_msgList .layer_slideTitle,.li_msgList .layer_slideList").mouseover(function(){canHide=false;$("#ing_push").hide();if($(".list_msgList a").length==0){var msg=$("#push_cnt").html();$(".list_msgList").html(msg);var width=$("#ing_push").width();$("#cls_pnlHeader .layer_newsList").css("width",width-5);$("#cls_pnlHeader .layer_newsList .layer_cnt").css("width",width-16);$("#cls_pnlHeader .layer_newsList .layer_cnt li").css("width",width-14);$("#cls_pnlHeader .layer_newsList .layer_cnt li a").css("width",width-26);$(".list_msgList").show();}}).mouseout(function(){canHide=true;$(".list_msgList").html();if(!isclosed){$("#ing_push").show();}});}catch(e){}
var isIe6=false;if($.browser!=null&&$.browser.msie){if($.browser.version=='6.0'){isIe6=true;}}}
try{if(nosave){return;}
HJBulo.fun.setCookie("bulo_tips_201208_nc",$.toJSON(data),30,"/");}
catch(e){}}
(function(){var win=window;if(win['HJBulo']===undefined)win['HJBulo']={};var HJBulo=win['HJBulo'];HJBulo.fun={getCookie:function(name){var cookie_start=document.cookie.indexOf(name);var cookie_end=document.cookie.indexOf(";",cookie_start);return cookie_start==-1?'':unescape(document.cookie.substring(cookie_start+name.length+1,(cookie_end>cookie_start?cookie_end:document.cookie.length)));},setCookie:function(cookieName,cookieValue,seconds,path,domain,secure){if(!domain){domain=this.getHost();}
var expires=new Date();expires.setTime(expires.getTime()+seconds*1000);document.cookie=escape(cookieName)+'='+escape(cookieValue)
+(expires?'; expires='+expires.toGMTString():'')
+(path?'; path='+path:'/')
+(domain?'; domain='+domain:'')
+(secure?'; secure':'');},getHost:function(url){var host="null";if(typeof url=="undefined"||null==url)
{url=window.location.host;}
var hosts=url.split(".");if(hosts.length>1){return hosts[hosts.length-2]+"."+hosts[hosts.length-1];}
return hosts[hosts.length-1];}}})();function GetMsg(){var cookieMsg=HJBulo.fun.getCookie("bulo_tips_201208_nc");if(cookieMsg&&cookieMsg!=null){GetNewMsg($.evalJSON(cookieMsg),true);return;}
var userid=0;try{userid=HJ_New_BuloID;}
catch(e){}
$.ajax({type:"get",url:"http://hjapi.hujiang.com/notify/v1/tips/c/Jsonp/"+userid,dataType:"jsonp",jsonp:"callback",jsonpCallback:"successCallback",error:errorCallback});}
function closeMsg(){isclosed=true;$("#ing_push").hide();HJBulo.fun.setCookie("bulo_tips_201208_nc",null,1,"/");var mcCount=parseInt($("#ing_push span.tips_data_mcount").text());if(!isNaN(mcCount)){HJBulo.fun.setCookie("bulo_tips_201208_nomc",mcCount,8*60*60,"/");}
$.ajax({url:"http://t.hujiang.com/service/json_closemsg.ashx?callback=?",dataType:"jsonp",jsonp:"callback",timeout:'1000'});$.ajax({url:"http://api.hujiang.com/json_closemsg.ashx?op=nc",dataType:"jsonp",jsonp:"callback",timeout:'1000'});$.ajax({url:"http://api.hujiang.com/json_closemsg.ashx?op=pc",dataType:"jsonp",jsonp:"callback",timeout:'1000'});}
var successCallback=function(data,status){if(data){getMsgFromOld(data,HJ_New_BuloID);}}
var getMsgFromOld=function(data,uid){newData=data;$.ajax({url:"http://api.hujiang.com/json_getmsg.ashx?type=1&notice=1&callback=?&userid="+uid,dataType:"jsonp",jsonp:"callback",timeout:'1000'});}
var errorCallback=function(data){throw new Error("Can't not get data!");};$(function(){$("#ing_push a").click(function(){HJBulo.fun.setCookie("bulo_tips_201208_nc",null,1,"/");});})
var showWindown=true;var templateSrc="http://bulo.yeshj.com/app";function tipsWindown(title,content,width,height,drag,time,showbg,cssName){$("#windown-box").remove();var width=width>=950?this.width=950:this.width=width;var height=height>=527?this.height=527:this.height=height;if(showWindown==true){var simpleWindown_html=new String;simpleWindown_html="<div id=\"windownbg\" style=\"height:"+$(document).height()+"px;filter:alpha(opacity=0);opacity:0;z-index: 999901\"></div>";simpleWindown_html+="<div id=\"windown-box\">";simpleWindown_html+="<div id=\"windown-title\"><h2></h2><span id=\"windown-close\">关闭</span></div>";simpleWindown_html+="<div id=\"windown-content-border\"><div id=\"windown-content\"></div></div>";simpleWindown_html+="</div>";$("body").append(simpleWindown_html);show=false;}
contentType=content.substring(0,content.indexOf(":"));content=content.substring(content.indexOf(":")+1,content.length);switch(contentType){case"text":$("#windown-content").html(content);break;case"id":$("#windown-content").html($("#"+content+"").html());break;case"img":$("#windown-content").ajaxStart(function(){$(this).html("<img src='"+templateSrc+"/images/loading.gif' class='loading' />");});$.ajax({error:function(){$("#windown-content").html("<p class='windown-error'>加载数据出错...</p>");},success:function(html){$("#windown-content").html("<img src="+content+" alt='' />");}});break;case"url":var content_array=content.split("?");$("#windown-content").ajaxStart(function(){$(this).html("<img src='"+templateSrc+"/images/loading.gif' class='loading' />");});$.ajax({type:content_array[0],url:content_array[1],data:content_array[2],error:function(){$("#windown-content").html("<p class='windown-error'>加载数据出错...</p>");},success:function(html){$("#windown-content").html(html);}});break;case"iframe":$("#windown-content").html("<img src='"+templateSrc+"/images/loading.gif' class='loading' />");$.ajax({error:function(){$("#windown-content").html("<p class='windown-error'>加载数据出错...</p>");},success:function(html){$("#windown-content").html("<iframe src=\""+content+"\" width=\"100%\" height=\""+parseInt(height)+"px"+"\" scrolling=\"auto\" frameborder=\"0\" marginheight=\"0\" marginwidth=\"0\"></iframe>");}});}
$("#windown-title h2").html(title);if(showbg=="true"){$("#windownbg").show();}else{$("#windownbg").remove();};$("#windownbg").animate({opacity:"0.5"},"normal");$("#windown-box").show();if(height>=527){$("#windown-title").css({width:(parseInt(width)+22)+"px"});$("#windown-content").css({width:(parseInt(width)+17)+"px",height:height+"px"});}else{$("#windown-title").css({width:(parseInt(width)+10)+"px"});$("#windown-content").css({width:width+"px",height:height+"px"});}
var cw=document.documentElement.clientWidth,ch=document.documentElement.clientHeight,est=document.documentElement.scrollTop;var _version=$.browser.version;if(_version==6.0){$("#windown-box").css({left:"50%",top:(parseInt((ch)/2)+est)+"px",marginTop:-((parseInt(height)+53)/2)+"px",marginLeft:-((parseInt(width)+32)/2)+"px",zIndex:"999999"});}else{$("#windown-box").css({left:"50%",top:"50%",marginTop:-((parseInt(height)+53)/2)+"px",marginLeft:-((parseInt(width)+32)/2)+"px",zIndex:"999999"});};var Drag_ID=document.getElementById("windown-box"),DragHead=document.getElementById("windown-title");var moveX=0,moveY=0,moveTop,moveLeft=0,moveable=false;if(_version==6.0){moveTop=est;}else{moveTop=0;}
var sw=Drag_ID.scrollWidth,sh=Drag_ID.scrollHeight;DragHead.onmouseover=function(e){if(drag=="true"){DragHead.style.cursor="move";}else{DragHead.style.cursor="default";}};DragHead.onmousedown=function(e){if(drag=="true"){moveable=true;}else{moveable=false;}
e=window.event?window.event:e;var ol=Drag_ID.offsetLeft,ot=Drag_ID.offsetTop-moveTop;moveX=e.clientX-ol;moveY=e.clientY-ot;document.onmousemove=function(e){if(moveable){e=window.event?window.event:e;var x=e.clientX-moveX;var y=e.clientY-moveY;if(x>0&&(x+sw<cw)&&y>0&&(y+sh<ch)){Drag_ID.style.left=x+"px";Drag_ID.style.top=parseInt(y+moveTop)+"px";Drag_ID.style.margin="auto";}}}
document.onmouseup=function(){moveable=false;};Drag_ID.onselectstart=function(e){return false;}}
$("#windown-content").attr("class","windown-"+cssName);var closeWindown=function(){$("#windownbg").remove();$("#windown-box").fadeOut("slow",function(){$(this).remove();});}
if(time==""||typeof(time)=="undefined"){$("#windown-close").click(function(){$("#windownbg").remove();$("#windown-box").fadeOut("slow",function(){$(this).remove();});});}else{setTimeout(closeWindown,time);}}
var timerIngBoxClose=null;var ingSender=null;(function(){ingSender=function(){this.callback_success=function(){};this.op={toplimit:39,top:'60',backurl:''}
this.init();}
ingSender.prototype={init:function(){var self=this;$(document).keyup(function(e){if(window.event){e=event;}
else{e=arguments[0];}
if(e.ctrlKey&&e.keyCode==120){var frame_ing=$(".pnl_ingSender_frame");if(frame_ing.length>0){self.closeSendBox(frame_ing);}
else{self.showSendBox();}}})},addCookie:function(objName,objValue,objHours,domain){var str=objName+"="+escape(objValue);if(objHours>0){var date=new Date();var ms=objHours*3600*1000*100;date.setTime(date.getTime()+ms);str+=";expires="+date.toGMTString();if(domain!=null&&domain.length>0){str+=";domain="+domain;}}
document.cookie=str+";path=/";},getCookie:function(objName){var arrStr=document.cookie.split("; ");for(var i=0;i<arrStr.length;i++){var temp=arrStr[i].split("=");if(temp[0]==objName)return unescape(temp[1]);}
return null;},delCookie:function(name){var date=new Date();date.setTime(date.getTime()-10000);document.cookie=name+"=a; expires="+date.toGMTString();},checkIsLogin:function()
{var islogin=true;var loginCookie=this.getCookie("ClubAuth");if(loginCookie==null||loginCookie==""){$.ajax({url:"http://t.hujiang.com/api/CheckLogin.ashx?callback=?",dataType:"jsonp",jsonp:"callback",timeout:'1000',async:false,success:function(result)
{islogin=result==1;}});}
return islogin;},showSendBox:function(inCnt,imgUrl){var self=this;if(!this.checkIsLogin())return;var screenHeight=$(window).height();var screenWidth=$(window).width();this.addCookie("ing_sendboxState",1,1,'.hujiang.com');var position="fixed";if(inCnt==null||inCnt.length==0)
{inCnt="";}
var isIe6=false;if($.browser.msie){if($.browser.version=='6.0'){isIe6=true;}}
if(isIe6)
{position="absolute";screenHeight=$("body").height();this.op.top='60px';}
var url="http://t.hujiang.com/sendbox/?limit="+this.op.toplimit+"&top="+this.op.top+"&cnt="+inCnt+"&backurl="+this.op.backurl;if(imgUrl!=null&&imgUrl!="")
{url+="&img="+imgUrl;}
var str="<iframe class='pnl_ingSender_frame' style=\"width:"+screenWidth+"px;height:"+screenHeight+"px;z-index:9999999999;position:"+position+";top:0px;border:0px;left:0px;display:none;\" scrolling=\"no\" frameborder=\"no\"  allowtransparency=\"true\" src=\""+url+"\"></iframe>";$("body").append(str);$(".pnl_ingSender_frame").fadeIn(200);setTimeout(function(){self.intervalCloseBox($(".pnl_ingSender_frame"));},500);},intervalCloseBox:function(obj){var self=this;timerIngBoxClose=setInterval(function(){var value=self.getCookie("ing_sendboxState");if(value=="0"){self.closeSendBox(obj);}
else if(value=="2"){self.closeSendBox(obj);self.callback_success();}
else if(value=="3"){self.closeSendBox(obj);self.showSuccess('保存成功',true,3000);}},100)},closeSendBox:function(obj){clearTimeout(timerIngBoxClose);$(obj).remove();},showSuccess:function(content,autoClose,autoTime){var str="<div class='ingSender_winmedal-box' style='display:none; position: fixed;_position: absolute;-moz-border-radius:5px;-webkit-border-radius: 5px;-khtml-border-radius: 5px;border:0;_border:2px solid #97ACD2;background:url(http://t.hujiang.com/images/transBG.png) no-repeat;_background:white;text-align: left;left: 50%;top: 50%;margin-top:-130px;margin-left: -196px;z-index: 999999;'><div style='background:#FFF;line-height: 22px;margin: 5px;padding: 12px 0 10px 5px;position: relative;top: -1px;'><span onclick=\"$(this).parents('.ingSender_winmedal-box').hide(300)\" style=\"position: absolute;right: 10px;top: 8px;width: 16px;height: 16px;text-indent: -10em;overflow: hidden;background: url(http://t.hujiang.com/images/ico_tip_win_close.gif) no-repeat;cursor: pointer;display:block;\">Close</span><div style='width: 250px;height: 35px;line-height:35px;padding-left:10px;'><img style='float:left; margin:4px 15px 0px 0px;' src='http://t.hujiang.com/images/ico_right_answer.gif' /> <span class='big gray'>"+content+"</span></div></div></div>";if(autoTime==null)
{autoTime=1500;}
$(".ingSender_winmedal-box").remove();$("body").append(str);$(".ingSender_winmedal-box").show(300);if(autoClose){window.setTimeout(function(){$('.ingSender_winmedal-box').hide(300)},autoTime);}}}})()